on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    name: Publish to Github Pages
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: '22'

      - name: Download TradingView
        uses: actions/checkout@v2
        with:
          ssh-key: ${{ secrets.PRIVATE_SSH_KEY }}
          repository: OrderlyNetwork/tradingview
          path: public/tradingview

      - name: Build
        run: |
          yarn install
          export VITE_USE_ADVANCED_CHARTS=true
          export VITE_BASE=/example-dex
          export BASE=/example-dex/
          yarn build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./build/client

  deploy:
    needs: build

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
